// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysewjsyrhdsevtygftmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZXdqc3lyaGRzZXZ0eWdmdG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTE3NTAsImV4cCI6MjA3MTg4Nzc1MH0.91ODi-9x_B1a0sP1mzzYzjD8Bm7OL1JSWrCh4Q3Unvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});